# Generated by Django 5.2.3 on 2025-06-20 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile_picture', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.users')),
                ('is_loyal', models.BooleanField(default=False)),
            ],
            bases=('users.users',),
        ),
        migrations.CreateModel(
            name='MamaMboga',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.users')),
                ('working_days', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
            ],
            bases=('users.users',),
        ),
    ]
