# Generated by Django 5.2.3 on 2025-06-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamamboga', 'Mama Mboga')], default='mamamboga', max_length=10),
        ),
    ]
