# Generated by Django 5.2.3 on 2025-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='Nairobi, Kenya', max_length=300),
        ),
    ]
