# Generated by Django 5.2.3 on 2025-07-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_usertype_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
