# Generated by Django 5.2.3 on 2025-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamamboga', 'Mama Mboga')], default='mamamboga', max_length=10),
        ),
    ]
