# Generated by Django 5.2.3 on 2025-07-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mamamboga',
            name='user',
        ),
    ]
