# Generated by Django 5.2.3 on 2025-07-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_remove_customer_user_remove_mamamboga_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='users_ptr',
        ),
        migrations.RemoveField(
            model_name='mamamboga',
            name='users_ptr',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='usertype',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='till_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['phone_number'], name='users_users_phone_n_7f0bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['role'], name='users_users_role_550aac_idx'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MamaMboga',
        ),
    ]
