# Generated by Django 5.2.3 on 2025-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customer_user_remove_mamamboga_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(default='Nairobi, Kenya', max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.URLField(max_length=1000),
        ),
    ]
