# Generated by Django 5.2.3 on 2025-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_admin_remove_customer_users_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_image',
            new_name='profile_picture',
        ),
    ]
