# Generated by Django 5.2.3 on 2025-07-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_user_image_users_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='profile_picture',
            new_name='user_image',
        ),
    ]
