# Generated by Django 5.2.3 on 2025-07-21 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_profile_picture_users_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_loyal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.users',),
        ),
        migrations.CreateModel(
            name='MamaMboga',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('working_days', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.users',),
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='users_users_phone_n_7f0bd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='users_users_role_550aac_idx',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='till_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_image',
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://example.com/default-profile-pic.jpg', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamamboga', 'Mama Mboga')], default='mamamboga', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(default='Nairobi, Kenya', max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
