# Generated by Django 5.2.3 on 2025-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customer_mamamboga_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamamboga', 'Mama Mboga'), ('admin', 'Admin')], default='mamamboga', max_length=10),
        ),
    ]
