# Generated by Django 5.2.3 on 2025-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=50),
        ),
    ]
