# Generated by Django 5.2.3 on 2025-07-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Unique Checkout Request ID from M-Pesa', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(default='25fe-4f8a-9a66-d5cbb202bfb439661', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='M-Pesa', help_text='Payment method', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction Receipt Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for payment', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_code',
            field=models.CharField(blank=True, help_text='M-Pesa Result Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_desc',
            field=models.TextField(blank=True, help_text='M-Pesa Result Description', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the transaction', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last updated'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant_request_id'], name='order_payme_merchan_adc2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='order_payme_checkou_7622ed_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='order_payme_status_59d707_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='order_payme_order_i_1ea8bc_idx'),
        ),
    ]
