# Generated by Django 5.2.3 on 2025-07-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='order_payme_order_i_5b689c_idx',
            old_name='order_payme_order_i_1ea8bc_idx',
        ),
    ]
