"""
Django settings for sokoconnect project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^a7fa_@qy+bi6(pn9d#w841h%92-qcb*h84f39ay%p381^kreo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reviews',
    'order',
    'users',
    'inventory',
    'api',
    'rest_framework',
   'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sokoconnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sokoconnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
       'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'HOST':'aws-0-eu-north-1.pooler.supabase.com',
        'PORT' : '5432',
        'USER':'postgres.vhiiixndtxeyaqzekmks',
        'PASSWORD' : '1321Nm!!!',
        'TEST': {
            'NAME':'test_sokoconnect'
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DARAJA_CONSUMER_KEY = 'niJ9gLDemh4EaLqsBfxAvsm0k6hBpOjRpAeDYW86gmVyTgSd'
DARAJA_CONSUMER_SECRET = '8QxlAcGjfBAHwbYRAWdvJIvBtAOmsw4vk62eACNHaky9exWQQIReA02HXoql9A0j'
DARAJA_SHORTCODE = '174379' 
DARAJA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
DARAJA_CALLBACK_URL = 'https://1234abcd.ngrok.io/api/payments/daraja-callback/'


# import os
# from pathlib import Path
# from decouple import config
# LIPANAMPESA_SHORTCODE = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
# LIPANAMPESA_PASSKEY = config('LIPANAMPESA_PASSKEY', default='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919')
# CONSUMER_KEY = 'niJ9gLDemh4EaLqsBfxAvsm0k6hBpOjRpAeDYW86gmVyTgSd'
# CONSUMER_SECRET = '8QxlAcGjfBAHwbYRAWdvJIvBtAOmsw4vk62eACNHaky9exWQQIReA02HXoql9A0j'
# BUSINESS_SHORT_CODE = '174379'
# TRANSACTION_TYPE = 'CustomerBuyGoodsOnline'
# CALL_BACK_URL = 'https://b968-41-90-172-243.ngrok-free.app'
# ACCOUNT_REFERENCE = 'CompanyXLTD'
# TRANSACTION_DESCRIPTION = 'Payment of x'
# ACCESS_TOKEN_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'
# API_RESOURCE_URL = 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest'

# BASE_DIR = Path(__file__).resolve().parent.parent


from decouple import config
import os
GEOPIFY_API_KEY = "d6ffdb356e7c4c428c35fcdb3a461ed6"
NOMINATIM_USER_AGENT = "sokoconnect_app"  
API_REQUEST_TIMEOUT = 5  