# Generated by Django 5.2.3 on 2025-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_category_remove_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('tomatoes', 'Tomatoes'), ('cucumber', 'Cucumber'), ('onion', 'Onion'), ('carrot', 'Carrot'), ('sukuma', 'Sukuma'), ('potato', 'Potato'), ('cabbage', 'Cabbage'), ('okra', 'Okra'), ('kale', 'Kale'), ('pumpkin_leaves', 'Pumpkin Leaves'), ('bell_pepper', 'Bell Pepper'), ('omena', 'Omena'), ('tilapia', 'Tilapia'), ('fish_ball', 'Fish Ball'), ('fulu_fish', 'Fulu Fish'), ('fish_skew', 'Fish Skew'), ('fish_stick', 'Fish Stick'), ('black_beans', 'Black Beans'), ('yellow_beans', 'Yellow Beans'), ('githeri', 'Githeri'), ('red_beans', 'Red Beans'), ('lentils', 'Lentils'), ('green_peas', 'Green Peas'), ('chick_peas', 'Chick Peas'), ('green_grams', 'Green Grams'), ('garlic', 'Garlic'), ('chilli', 'Chilli'), ('ginger', 'Ginger'), ('matoke', 'Matoke')], default=('tomatoes', 'Tomatoes'), max_length=50),
            preserve_default=False,
        ),
    ]
