# Generated by Django 5.2.3 on 2025-07-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fish', 'Fish'), ('cereal', 'Cereal'), ('others', 'Others')], default=('vegetable', 'Vegetable'), max_length=20),
            preserve_default=False,
        ),
    ]
