# Generated by Django 5.2.3 on 2025-07-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('bunch', 'Bunch'), ('kilogram', 'Kilogram'), ('cup', 'Cup'), ('piece', 'Piece')], max_length=50),
        ),
    ]
