# Generated by Django 5.2.3 on 2025-07-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_stock_unit'),
        ('users', '0008_alter_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='mamamboga_discount', to='users.users'),
        ),
        migrations.AlterField(
            model_name='loyalcustomerdiscount',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount', to='users.users'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.users'),
        ),
    ]
