# Generated by Django 5.2.4 on 2025-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_discount_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fish', 'Fish'), ('cereal', 'Cereal'), ('others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('tomatoes', 'Tomatoes'), ('cucumber', 'Cucumber'), ('onion', 'Onion'), ('carrot', 'Carrot'), ('sukuma', 'Sukuma'), ('potato', 'Potato'), ('cabbage', 'Cabbage'), ('okra', 'Okra'), ('kale', 'Kale'), ('pumpkin_leaves', 'Pumpkin Leaves'), ('bell_pepper', 'Bell Pepper'), ('omena', 'Omena'), ('tilapia', 'Tilapia'), ('fish_ball', 'Fish Ball'), ('fulu_fish', 'Fulu Fish'), ('fish_skew', 'Fish Skew'), ('fish_stick', 'Fish Stick'), ('black_beans', 'Black Beans'), ('yellow_beans', 'Yellow Beans'), ('githeri', 'Githeri'), ('red_beans', 'Red Beans'), ('lentils', 'Lentils'), ('green_peas', 'Green Peas'), ('chick_peas', 'Chick Peas'), ('green_grams', 'Green Grams'), ('garlic', 'Garlic'), ('chilli', 'Chilli'), ('ginger', 'Ginger'), ('matoke', 'Matoke')], max_length=200),
        ),
    ]
