# Generated by Django 5.2.3 on 2025-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_category_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=50000),
        ),
    ]
