# Generated by Django 5.2.3 on 2025-07-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_discount_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='mamamboga_discount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loyalcustomerdiscount',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
