# Generated by Django 5.2.3 on 2025-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamaMboga', 'MamaMboga')], default='customer', max_length=20),
        ),
    ]
