# Generated by Django 5.2.3 on 2025-06-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('mamamboga', 'MamaMboga')], max_length=20),
        ),
    ]
