# Generated by Django 5.2.3 on 2025-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
