# Generated by Django 5.2.3 on 2025-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(max_length=10),
        ),
    ]
