# Generated by Django 5.2.3 on 2025-06-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorReview',
            new_name='Review',
        ),
    ]
