# Generated by Django 5.2.3 on 2025-07-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_customer_remove_review_vendor'),
        ('users', '0008_alter_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(default=1, limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to='users.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(default=2, limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='mamamboga_review', to='users.users'),
            preserve_default=False,
        ),
    ]
