# Generated by Django 5.2.3 on 2025-07-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_customer_alter_review_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='mamamboga_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
