# Generated by Django 5.2.3 on 2025-07-09 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_items', models.PositiveIntegerField()),
                ('quantity_of_items', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.customer')),
                ('products', models.ManyToManyField(related_name='carts', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.mamamboga')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('merchant_request_id', models.CharField(default='test123', max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='Unique Checkout Request ID from M-Pesa', max_length=100, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, help_text='M-Pesa Result Code', max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, help_text='M-Pesa Result Description', null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa Transaction Receipt Number', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for payment', max_length=15, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date and time of the transaction', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last updated')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'indexes': [models.Index(fields=['merchant_request_id'], name='order_payme_merchan_adc2ac_idx'), models.Index(fields=['checkout_request_id'], name='order_payme_checkou_7622ed_idx'), models.Index(fields=['status'], name='order_payme_status_59d707_idx'), models.Index(fields=['order_id'], name='order_payme_order_i_1ea8bc_idx')],
            },
        ),
    ]
