# Generated by Django 5.2.3 on 2025-07-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
