# Generated by Django 5.2.3 on 2025-07-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_customer_alter_order_vendor'),
        ('users', '0008_alter_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.users'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'usertype': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='users.users'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'usertype': 'mamamboga'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='users.users'),
        ),
    ]
