# Generated by Django 5.2.3 on 2025-07-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_payment_options_remove_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
    ]
