# Generated by Django 5.2.3 on 2025-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'paid')], default='pending', help_text='Payment status', max_length=20),
        ),
    ]
